### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by cojo1989** [sstokic-tgm/Gladiatorcheatz-v2.1#22] opened 2019-05-05 10:41 UTC
`  Logger.cpp
  Miscellaneous.cpp
  Utils.cpp
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(10): error C2039: 'string': is not a member of 'std' (compiling source file helpers\Utils.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\vector(19): note: see declaration of 'std' (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(10): error C2061: syntax error: identifier 'string' (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(17): error C2039: 'string': is not a member of 'std' (compiling source file helpers\Utils.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\vector(19): note: see declaration of 'std' (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(17): error C3646: 'm_Text': unknown override specifier (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(17): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(12): error C2039: 'm_Text': is not a member of 'MessageInfo' (compiling source file helpers\Utils.cpp)
  C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(8): note: see declaration of 'MessageInfo' (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(12): error C2065: 'text': undeclared identifier (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(13): error C2065: 'color': undeclared identifier (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(14): error C2065: 'time': undeclared identifier (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(27): error C2039: 'string': is not a member of 'std' (compiling source file helpers\Utils.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\vector(19): note: see declaration of 'std' (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(27): error C2061: syntax error: identifier 'string' (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(10): error C2039: 'string': is not a member of 'std' (compiling source file features\Logger.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\vector(19): note: see declaration of 'std' (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(10): error C2061: syntax error: identifier 'string' (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(17): error C2039: 'string': is not a member of 'std' (compiling source file features\Logger.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\vector(19): note: see declaration of 'std' (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(17): error C3646: 'm_Text': unknown override specifier (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(17): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(12): error C2039: 'm_Text': is not a member of 'MessageInfo' (compiling source file features\Logger.cpp)
  C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(8): note: see declaration of 'MessageInfo' (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(12): error C2065: 'text': undeclared identifier (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(13): error C2065: 'color': undeclared identifier (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(14): error C2065: 'time': undeclared identifier (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(27): error C2039: 'string': is not a member of 'std' (compiling source file features\Logger.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\vector(19): note: see declaration of 'std' (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(27): error C2061: syntax error: identifier 'string' (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(29): error C2065: 'message': undeclared identifier (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(29): error C2065: 'color': undeclared identifier (compiling source file helpers\Utils.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(29): error C2065: 'message': undeclared identifier (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(29): error C2065: 'color': undeclared identifier (compiling source file features\Logger.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(14): warning C4244: '=': conversion from 'int' to 'float', possible loss of data (compiling source file features\Miscellaneous.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\math\QAngle.hpp(32): error C2039: 'isfinite': is not a member of 'std' (compiling source file features\Miscellaneous.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\vector(19): note: see declaration of 'std' (compiling source file features\Miscellaneous.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\math\QAngle.hpp(158): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data (compiling source file features\Miscellaneous.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\math\QAngle.hpp(196): warning C4244: '=': conversion from 'double' to 'float', possible loss of data (compiling source file features\Miscellaneous.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\math\QAngle.hpp(209): warning C4244: '=': conversion from 'double' to 'float', possible loss of data (compiling source file features\Miscellaneous.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\math\QAngle.hpp(222): warning C4244: '=': conversion from 'double' to 'float', possible loss of data (compiling source file features\Miscellaneous.cpp)
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.cpp(48): error C2039: 'm_Text': is not a member of 'MessageInfo'
  C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(8): note: see declaration of 'MessageInfo'
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.cpp(48): error C2661: 'Visuals::DrawString': no overloaded function takes 5 arguments
C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\helpers\Utils.cpp(278): error C2660: 'Logger::add': function does not take 2 arguments
  C:\Users\z3ro_\Desktop\Gladiatorcheatz-v2.1-master\features\Logger.hpp(27): note: see declaration of 'Logger::add' (compiling source file helpers\Utils.cpp)
`

I put the library i done everything and i still get this errors, can you help me please? Appreciate thank you !

**Comment by cojo1989** [comment] 2019-05-05 11:12
![erorr 1](https://user-images.githubusercontent.com/36346905/57193030-bf9ef800-6f3f-11e9-8337-9af5525b5ae2.png)
![lib](https://user-images.githubusercontent.com/36346905/57193031-bf9ef800-6f3f-11e9-9e46-30de2584adc6.png)

**Comment by cojo1989** [comment] 2019-05-10 23:13
Nobody can help me?

**Comment by KaylinOwO** [comment] 2019-05-17 02:18
Most likely using a Windows SDK that isn't properly/fully installed, try changing it to something else (assuming there's more than 1 option)

**Comment by sstokic-tgm** [comment] 2019-05-28 12:19
If you still have troubles, do "Retarget solution".

**Comment by cojo1989** [comment] 2019-05-28 12:21
I give up buddy its to much for me 😂😂😂. I just wanted to test it nothing more. To bad its kinda dead project :(

**Comment by sstokic-tgm** [comment] 2019-05-28 12:24
Its not dead bruh :disappointed_relieved:
Do you use VS2017? And v141 toolset? It should work then :thumbsup:

**Comment by cojo1989** [comment] 2019-05-28 12:26
I think its exacly what i use give me 5 min. I will try again.

**Comment by cojo1989** [comment] 2019-05-28 12:30
v142 
SDK 10.0
And i got same errors... Release / x86

**Comment by sstokic-tgm** [comment] 2019-05-28 12:32
Hmmmm, have a look, where Logger.hpp/.cpp is located physically there.
Like if the file is located inside features/

Also look in the project explorer if Logger.hpp/.cpp is under the features filter. If not add it. (Right click -> add existing file)

**Comment by cojo1989** [comment] 2019-05-28 12:42
Now i got warnings but it`s compileing.
Chams not working.

`Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4244	'=': conversion from 'int' to 'float', possible loss of data (compiling source file helpers\Utils.cpp)	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\features\logger.hpp	14	
Warning	C4390	';': empty controlled statement found; is this the intent?	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\features\antiaim.cpp	126	
Warning	C4244	'=': conversion from 'int' to 'float', possible loss of data (compiling source file features\Logger.cpp)	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\features\logger.hpp	14	
Warning	C4244	'=': conversion from 'int' to 'float', possible loss of data (compiling source file features\Miscellaneous.cpp)	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\features\logger.hpp	14	
Warning	C4305	'argument': truncation from 'double' to 'float'	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\imgui\imgui.cpp	6878	
Warning	C4804	'>': unsafe use of type 'bool' in operation	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\features\visuals.cpp	570	
Warning	C4838	conversion from 'int' to 'unsigned char' requires a narrowing conversion	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\features\visuals.cpp	980	
Warning	C4138	'*/' found outside of comment (compiling source file Handlers.cpp)	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\gamehooking.hpp	68	
Warning	C5033	'register' is no longer a supported storage class	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\misc\checksum_md5.cpp	27	
Warning	C4138	'*/' found outside of comment (compiling source file Install.cpp)	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\gamehooking.hpp	68	
Warning	C4715	'<lambda_d35ae56936051db81bca931d35ea9be8>::operator()': not all control paths return a value	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\features\skinchanger.cpp	257	
Warning	C4715	'<lambda_72f9490ace2ba7460a68cc8e63cefe4c>::operator()': not all control paths return a value	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\features\skinchanger.cpp	249	
Warning	C4715	'C_BasePlayer::GetArmorName': not all control paths return a value	Gladiatorcheatz v2	c:\users\z3ro_\desktop\gladiatorcheatz-v2.1-master\gladiatorcheatz-v2.1-master\structs.hpp	363	
`

**Comment by sstokic-tgm** [comment] 2019-05-28 12:47
Warnings are okay, didn't fix all of them hehe.

Well dunno about the chams, it works okay at my place

**Comment by cojo1989** [comment] 2019-05-28 12:49
Hmm, can you add a version only of HvH on github? And to be upgraded to latest VS?

**Comment by sstokic-tgm** [comment] 2019-05-28 12:51
Well I use VS2017 atm since 2k19 has a few problems which are useless and need to be fixed. A hvh only version doesn't exist as a single version though, but my v3 was intended to be hvh only but no time.

I guess you have to be okay with this one for now :see_no_evil:

Will close this issue as of compile errors are fixed. If you encounter something feel free to open a new issue

**Closed by sstokic-tgm** 2019-05-28 12:51 UTC
